baseURL: 'https://zippy-chimera-0ef916.netlify.app/'
languageCode: en-us
title: Car Blog
theme: PaperMod

params:
    homeInfoParams:
        Title: Welcome!
        Content: My name is Tariq Rahman

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/tariqrahman"
        - name: "Instagram"
          url: "https://www.instagram.com/tariqrahmann/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


menu:
    main:
        - identifier: search
          name: search
          url: /search/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - indentifier: archives
          name: archives
          url: /archives/
          weight: 30