baseURL: 'https://trexreviews.com/'
languageCode: en-us
title: TReviews
theme: PaperMod

params:
    profileMode:
        enabled: true
        title: "Welcome to TReviews 🦖" # optional default will be site title
        subtitle: "Check out my collection of biased automotive reviews"
        # imageUrl: "https://i.ibb.co/pL7qTkx/IMG-9850.jpg" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Posts
              url: "/posts"
            - name: T-Term
              url: "https://tariqrahmansite.vercel.app/"

    # homeInfoParams:
    #     Title: Welcome to TReviews 🦖
    #     Content: I write biased, blunt, & brilliant automotive reviews. Check 'em out below`:`

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/tariqrahman"
        - name: "Instagram"
          url: "https://www.instagram.com/tariqrahmann/"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/tariq-rahman-56a684187/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


menu:
    main:
        - identifier: search
          name: search
          url: /search/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - indentifier: archives
          name: archives
          url: /archives/
          weight: 30